# Generated by Django 3.0.8 on 2021-01-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255, verbose_name='Imię i nazwisko')),
                ('order_address_1', models.CharField(max_length=1024, verbose_name='Ulica oraz numer domu/mieszkania')),
                ('order_address_2', models.CharField(max_length=1024, verbose_name='Miejscowość')),
                ('post_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('order_email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('order_amount', models.PositiveIntegerField(verbose_name='Ilość')),
            ],
        ),
    ]
