# Generated by Django 3.0.8 on 2020-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('order_address_1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('order_address_2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('post_code', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('order_email', models.EmailField(max_length=254)),
                ('order_amount', models.IntegerField()),
            ],
        ),
    ]
