# Generated by Django 3.0.8 on 2021-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210129_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_name',
        ),
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='fullname', max_length=50, verbose_name='Imię i nazwisko'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_address_1',
            field=models.CharField(max_length=350, verbose_name='Ulica oraz numer domu/mieszkania'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_address_2',
            field=models.CharField(max_length=350, verbose_name='Miejscowość'),
        ),
    ]
